### ISSUE TITLE
fork from v16.0.9?

### ISSUE THREAD

**Issue by jadertao** [Game-X-Coin/eosjs-rn#2]
this repo is forked from beta v20.0.1, which is still in develop and lacks some important api, so how about fork from v.16.0.9.

**Comment by ehnawh** [comment]
I added eosjs-rn from v16.0.9. you cat use it by typing 'npm install eosjs-rn@16.0.9' or 'yarn add eosjs-rn@16.0.9'.
but, I removed 'function wasmCodeOverride in structs.js' and 'test code from eosjs-keygen' for compatibility reasons.


- [eosjs-rn npm](https://www.npmjs.com/package/eosjs-rn/v/16.0.9)
- [react-native-eosjs1 branch](https://github.com/Game-X-Coin/eosjs-rn/tree/react-native-eosjs1)

**Comment by JadeTao** [comment]
many thanks.
btw, `src/ripemd.js` uses `Proxy` which is not supported in RN. This file is imported only in `src/eosjs-numeric`.
maybe it can use `src/ripemd.es5.js` instead.

**Comment by JadeTao** [comment]
I find a way to avoid `Proxy`. 
see https://gist.github.com/wlzla000/bac83df6d3c51916c4dd0bc947e46947
and made a PR.

**Comment by ehnawh** [comment]
thanks @JadeTao 
i merged your PR. v
The reason why eosjs did not write ripemd5 in eosjs-ecc is directly implemented it is because it did not provide ripemd5 in eosjs-ecc. So I added ripemd5 api to eosjs-ecc-rn to use.
I thought it would be better to use the module eosjs-ecc api instead of using ripemd5.js as it is.
patch [eosjs-rn@20.0.0-beta2.1](https://www.npmjs.com/package/eosjs-rn/v/20.0.0-beta2.1)
